"""0030 — Physical split of dim_pl_structure into three statement-structure tables.

APPROVED PRODUCT DECISION (overrides seed_cf_structure.py's documented "Option B")
-----------------------------------------------------------------------------------
Until now ``dim_pl_structure`` held THREE statement types in one table, banded by
``sort_order`` and tagged by ``line_code`` / ``kpi_code``:

  * P&L rows : sort_order < 1000   (kpi_code NULL or a real code; not BS_/CF_)
  * BS  rows : sort_order 1000-1999 (line_code LIKE 'BS_%', kpi_code LIKE 'BS:%')
  * CF  rows : sort_order 2000+     (line_code LIKE 'CF_%', kpi_code LIKE 'CF%')

This migration PHYSICALLY splits the BS and CF rows out into two new tables with
the SAME column set (``dim_bs_structure`` / ``dim_cf_structure``), leaving
``dim_pl_structure`` P&L-only.  The copy predicates MIRROR the reader row-predicates
exactly so nothing is lost or duplicated:

  * CF : ``line_code LIKE 'CF\\_%' ESCAPE '\\' OR kpi_code LIKE 'CF%'``
         (== ``fin_compat_cf._is_cf_structure_row``)
  * BS : the FULL ``fin_compat_bs._is_bs_structure_row`` acceptance set
         (``sort_order >= 1000`` OR ``kpi_code LIKE 'BS:%'`` OR
          ``line_code LIKE 'BS\\_%'`` OR ``line_code IN (AR,INVENTORY,AP,CASH,
          EQUITY)``) **AND NOT** the CF set above.  The ``AND NOT CF`` is essential:
          the reader's ``sort_order >= 1000`` clause spans BOTH the BS band (1000-
          1999) AND the CF band (2000+), so without excluding CF it would swallow
          cash-flow rows.  Copying CF FIRST (by the CF predicate) then BS (by this
          reader-faithful predicate minus CF) makes the split LOSS-FAITHFUL to the
          readers: every row a statement reader would accept lands in exactly one of
          the three tables, and no BS-reader-visible row (e.g. a ``sort_order>=1000``
          or alias-coded row that the old narrow ``BS_/BS:`` predicate missed) is
          dropped from BOTH BS and PL.

``sort_order`` values are copied UNCHANGED (no re-basing) so no downstream ordering
shifts.  The surrogate PK ``pl_line_id`` is kept as the column NAME in both new
tables (readers ``SELECT pl_line_id`` verbatim) but its VALUES are regenerated by
the SERIAL default — no reader keys on the PK value (they key on line_code /
sort_order), so this is behaviour-preserving.

ROUND-TRIP: ``downgrade`` copies every row back into ``dim_pl_structure`` (all data
columns + sort_order + line_code preserved) and drops the two tables, restoring the
pre-split contents exactly (row-for-row on the data columns; only the surrogate
pl_line_id is re-minted).
"""
from __future__ import annotations

from alembic import op

revision = "0030_split_statement_structures"
down_revision = "0029_mart_overview_wc_top"
branch_labels = None
depends_on = None


# Column set copied verbatim from dim_pl_structure (migration 0001), same defaults.
_STRUCT_COLUMNS_DDL = """
    pl_line_id    SERIAL PRIMARY KEY,
    sort_order    INTEGER NOT NULL UNIQUE,
    line_code     VARCHAR(64) NOT NULL UNIQUE,
    row_type      VARCHAR(16) NOT NULL DEFAULT 'mapping',
    balance_title VARCHAR(500) NOT NULL DEFAULT '',
    details       INTEGER,
    calc_type     INTEGER DEFAULT 1,
    level_2       VARCHAR(200),
    level_3       VARCHAR(200),
    level_4       VARCHAR(500),
    gl_account_id VARCHAR(32),
    invert_delta  BOOLEAN NOT NULL DEFAULT FALSE,
    is_bold       BOOLEAN NOT NULL DEFAULT FALSE,
    kpi_code      VARCHAR(64)
"""

# Explicit data-column list (excludes the SERIAL pl_line_id so it regenerates).
_COPY_COLS = (
    "sort_order, line_code, row_type, balance_title, details, calc_type, "
    "level_2, level_3, level_4, gl_account_id, invert_delta, is_bold, kpi_code"
)

# Reader-faithful row predicates.
_CF_PREDICATE = r"(line_code LIKE 'CF\_%' ESCAPE '\' OR kpi_code LIKE 'CF%')"
# BS mirrors fin_compat_bs._is_bs_structure_row (sort_order>=1000 OR BS:*/BS_* OR
# the fixed aliases) MINUS the CF set — the sort_order>=1000 clause spans the CF
# band too, so CF must be excluded to keep the BS/CF/PL partition clean & lossless.
_BS_PREDICATE = (
    r"((sort_order >= 1000 OR kpi_code LIKE 'BS:%' "
    r"OR line_code LIKE 'BS\_%' ESCAPE '\' "
    r"OR line_code IN ('AR','INVENTORY','AP','CASH','EQUITY')) "
    r"AND NOT " + _CF_PREDICATE + ")"
)


def upgrade() -> None:
    op.execute(f"CREATE TABLE dim_bs_structure (\n{_STRUCT_COLUMNS_DDL}\n);")
    op.execute(f"CREATE TABLE dim_cf_structure (\n{_STRUCT_COLUMNS_DDL}\n);")

    # Copy CF rows, then BS rows (sort_order preserved, PK regenerated).
    op.execute(
        f"INSERT INTO dim_cf_structure ({_COPY_COLS}) "
        f"SELECT {_COPY_COLS} FROM dim_pl_structure "
        f"WHERE {_CF_PREDICATE};"
    )
    op.execute(
        f"INSERT INTO dim_bs_structure ({_COPY_COLS}) "
        f"SELECT {_COPY_COLS} FROM dim_pl_structure "
        f"WHERE {_BS_PREDICATE};"
    )

    # dim_pl_structure becomes P&L-only.
    op.execute(
        f"DELETE FROM dim_pl_structure WHERE {_CF_PREDICATE} OR {_BS_PREDICATE};"
    )

    op.execute(
        "COMMENT ON TABLE dim_bs_structure IS "
        "'Balance-sheet presentation structure (split out of dim_pl_structure in "
        "0030). BS rows only (line_code BS_* / kpi_code BS:*). Read by "
        "fin_compat_bs, balance_sheet, budget_service (BS positions).';"
    )
    op.execute(
        "COMMENT ON TABLE dim_cf_structure IS "
        "'Cash-flow presentation structure (split out of dim_pl_structure in 0030). "
        "CF rows only (line_code CF_* / kpi_code CF*). Read by fin_compat_cf.';"
    )


def downgrade() -> None:
    # Restore BS + CF rows back into dim_pl_structure (all data columns + sort_order
    # + line_code preserved; pl_line_id re-minted by the SERIAL default).
    op.execute(
        f"INSERT INTO dim_pl_structure ({_COPY_COLS}) "
        f"SELECT {_COPY_COLS} FROM dim_cf_structure;"
    )
    op.execute(
        f"INSERT INTO dim_pl_structure ({_COPY_COLS}) "
        f"SELECT {_COPY_COLS} FROM dim_bs_structure;"
    )
    op.execute("DROP TABLE dim_cf_structure;")
    op.execute("DROP TABLE dim_bs_structure;")
